### ISSUE TITLE
Support for PostgreSQL

### ISSUE THREAD

**Issue by Lathanael** [Infern1/phpDivinglog#2]
Hi.

I only have access to a PostgreSQL DB and would like to use this nice peace of software. Would it be possbile for you to include support for postgree?

(I already tried to inclued the pear DB for PostgreSQL but it seems like some things have to be adjusted and i am not familiar with php :( )

thanks

Lathanael

**Comment by Infern1** [comment]
I can research this, however how did you manage to import divelog data into PostgreSQL? If yes how did you do that so I can test PostgreSQL

**Comment by Lathanael** [comment]
I only had 1 test sample(found on the web) which i did edit by hand. For a larger log i would write a small programm or something similar which replaces certain chars so they are PG compaible.

Oh and i did find out that most of the changes are required in the sql files and the misc.inc.php -> parse_mysql_query to adjust for PG. Hope this helps

**Comment by Infern1** [comment]
Maybe a strange question, but why do you only have support for PostgreSQL?  If you can send me a dump of the postgresql dump I can test this.

**Comment by Lathanael** [comment]
I do get a free webspace provided from my student dorm(?), but unfortunatley they only have PostgreSQL on thier servers.

I'll soon get a new computer and will log 2 or 3 dives and send them to you, so you'll have some more and better data ;)

**Comment by Infern1** [comment]
no support for PostgreSQL will be implemented
