### ISSUE TITLE
Photo gallery issue's: undefined index

### ISSUE THREAD

**Issue by DieterKoblenz** [Infern1/phpDivinglog#8]
First, this is a long shot considering there hasn't been a commit in years. But I hope someone can assist me getting the gallery to work.

I've added 2 pictures from one dive. They work in the dive overview, but I can't open an gallery. Error log show's the following:

`[Sun Aug 15 12:21:06.971036 2021] [fcgid:warn] [pid 20875] [client x:55416] mod_fcgid: stderr: PHP Notice:  Undefined index: page_numbers in *private*/public_html/compile/087f13cc614260cc501fcf9766ff6475c72698cc_0.file.divegallery.tpl.php on line 51, referer: *private*/index.php?id=72
[Sun Aug 15 12:21:06.971168 2021] [fcgid:warn] [pid 20875] [client x:55416] mod_fcgid: stderr: PHP Notice:  Trying to get property of non-object in *private*/public_html/compile/087f13cc614260cc501fcf9766ff6475c72698cc_0.file.divegallery.tpl.php on line 51, referer: *private*/index.php?id=72
[Sun Aug 15 12:21:06.971175 2021] [fcgid:warn] [pid 20875] [client x:55416] mod_fcgid: stderr: PHP Notice:  Undefined index: image_link in *private*/public_html/compile/087f13cc614260cc501fcf9766ff6475c72698cc_0.file.divegallery.tpl.php on line 64, referer: *private*/index.php?id=72
[Sun Aug 15 12:21:06.971179 2021] [fcgid:warn] [pid 20875] [client x:55416] mod_fcgid: stderr: PHP Notice:  Trying to get property of non-object in *private*/public_html/compile/087f13cc614260cc501fcf9766ff6475c72698cc_0.file.divegallery.tpl.php on line 64, referer: *private*/index.php?id=72`

**Comment by Infern1** [comment]
Hi Dieter, yes you are right no commits for a long time. Currently on holiday. Will look when I am back next week. 

I am also working on complete rewrite.

**Comment by DieterKoblenz** [comment]
Thank you for your very prompt reply, even on holiday ;-)

We'll see where it goes. A rewrite sounds interesting as well, considering the changes in php.

I'm having similar problems in getting the trip overview showing the trip picture etc.

**Comment by Infern1** [comment]
Please check latest fixes to the template file:  https://github.com/Infern1/phpDivinglog/commit/d13720edc1819bd105d1c19a1ab44c65ac53e70a

Not sure if it helps.

Looking at your old code can be quite shocking....

**Comment by Infern1** [comment]
So a lot of fixes in, should be at least somewhat better

**Comment by DieterKoblenz** [comment]
Yeah this does help, I've got both the per-dive and total gallery working now. Thank you!

**Comment by Infern1** [comment]
Please check out latest release: https://github.com/Infern1/phpDivinglog/archive/refs/tags/v3.2.zip

Lot of other fixes are in. Also works with PHP 7.4 here

**Comment by DieterKoblenz** [comment]
Great work!  I've yet to change the PHP version back to 7.4, but it works without any adjustments on 7.1

To keep nagging at the same time: certifications are not working for me, not that I'm really interested in that bit, but I thought you should know.

I'm closing this issue, as the photo gallery seems in working order. Now I have to fill it with pics :)
