### ISSUE TITLE
 certifications are not working for me

### ISSUE THREAD

**Issue by Infern1** [Infern1/phpDivinglog#9]
Great work!  I've yet to change the PHP version back to 7.4, but it works without any adjustments on 7.1

To keep nagging at the same time: certifications are not working for me, not that I'm really interested in that bit, but I thought you should know.

I'm closing this issue, as the photo gallery seems in working order. Now I have to fill it with pics :)

_Originally posted by @DieterKoblenz in https://github.com/Infern1/phpDivinglog/issues/8#issuecomment-902810293_

**Comment by Infern1** [comment]
@DieterKoblenz can you explain a bit more on that. For me they are working

https://rob.lensen.nu/divelog/divestats.php?view=list

**Comment by DieterKoblenz** [comment]
![image](https://user-images.githubusercontent.com/2961896/130278650-f44d6207-54ba-466a-8fdc-ca004a72ceff.png)

I've got one cert added.

**Comment by DieterKoblenz** [comment]
I've added a dummy cert, now it gets filled.

So, one doesn't work. Two added do work.

**Comment by Infern1** [comment]
> I've added a dummy cert, now it gets filled.
> 
> So, one doesn't work. Two added do work.

Clear information, wil fix

**Comment by Infern1** [comment]
Fixed with: https://github.com/Infern1/phpDivinglog/commit/0ddeca7a836596c2e5b2f71ee801bc91cdc6f966
